# Generated by Django 6.0.9 on 2026-10-10 19:38

import django.db.models.deletion
import django.utils.timezone
import payments.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPointer',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('next_index', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_id', models.CharField(default=payments.models.default_order_id, max_length=64, unique=True, verbose_name='Номер заказа')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Назначение')),
                ('network', models.CharField(default='tron', max_length=16, verbose_name='Сеть')),
                ('asset', models.CharField(default='USDT', max_length=16, verbose_name='Актив')),
                ('address', models.CharField(max_length=64, unique=True, verbose_name='Адрес для оплаты')),
                ('derivation_index', models.PositiveIntegerField(unique=True, verbose_name='Индекс адреса')),
                ('amount_expected', models.DecimalField(decimal_places=6, max_digits=18, verbose_name='Сумма к оплате')),
                ('amount_received', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Получено')),
                ('status', models.CharField(choices=[('new', 'Создан'), ('pending', 'Ожидает оплату'), ('paid', 'Оплачен'), ('expired', 'Истёк'), ('canceled', 'Отменён')], default='new', max_length=16, verbose_name='Статус')),
                ('txid', models.CharField(blank=True, max_length=128, verbose_name='Транзакция')),
                ('confirmations', models.PositiveIntegerField(default=0, verbose_name='Подтверждений')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ('-created_at',),
            },
        ),
    ]
