# Generated by Django 6.0.9 on 2026-10-10 20:21

import django.db.models.deletion
import payments.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=6, default=0, max_digits=18, verbose_name='Баланс, USDT')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Баланс',
                'verbose_name_plural': 'Балансы',
            },
        ),
        migrations.DeleteModel(
            name='WalletPointer',
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ('-created_at',), 'verbose_name': 'Пополнение', 'verbose_name_plural': 'Пополнения'},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='derivation_index',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='address',
            field=models.CharField(max_length=64, verbose_name='Адрес для оплаты'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, default='Пополнение баланса', max_length=255, verbose_name='Назначение'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order_id',
            field=models.CharField(default=payments.models.default_order_id, max_length=64, unique=True, verbose_name='Номер пополнения'),
        ),
    ]
