from django.contrib import admin
from django.contrib.auth import views as auth
from django.urls import path
from core import views
from core import account_views as accounts, module_views as modules, payments
from core import app_api

urlpatterns = [
    path("", views.home, name="home"),
    path("health/", views.health, name="health"),
    path("prototype/", views.prototype, name="prototype"),
    path('app-api/session/', app_api.session, name='app_session'),
    path('app-api/results/', app_api.results, name='app_results'),
    path('app-api/results/save/', app_api.save_result, name='app_save_result'),
    path('app-api/results/share/', app_api.share_result, name='app_share_result'),
    path('app-api/recipients/', app_api.recipients, name='app_recipients'),
    path('results/', app_api.saved_results_page, name='saved_results'),
    path("register/", views.register, name="register"),
    path("login/", views.LoginView.as_view(template_name="auth.html", extra_context={"heading": "Войти"}), name="login"),
    path("logout/", auth.LogoutView.as_view(), name="logout"),
    path("people/", views.people, name="people"),
    path("messages/", views.inbox, name="inbox"),
    path("messages/start/<int:user_id>/", views.start_chat, name="start_chat"),
    path("messages/<uuid:conversation_id>/", views.chat, name="chat"),
    path("messages/<uuid:conversation_id>/history/", views.history, name="history"),
    path("admin/", admin.site.urls),
    path('profile/',accounts.profile,name='profile'),
    path('avatars/<int:user_id>/',accounts.avatar,name='avatar'),
    path('users/<int:user_id>/',accounts.public_profile,name='public_profile'),
    path('setup/<str:token>/',accounts.setup_owner,name='setup_owner'),
    path('password-reset/',auth.PasswordResetView.as_view(template_name='form.html',extra_context={'heading':'Сбросить пароль'},
        email_template_name='registration/reset_email.txt',subject_template_name='registration/reset_subject.txt'),name='password_reset'),
    path('password-reset/sent/',auth.PasswordResetDoneView.as_view(template_name='registration/reset_done.html'),name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',auth.PasswordResetConfirmView.as_view(template_name='form.html',extra_context={'heading':'Новый пароль'}),name='password_reset_confirm'),
    path('password-reset/complete/',auth.PasswordResetCompleteView.as_view(template_name='registration/reset_complete.html'),name='password_reset_complete'),
    path('password-change/',auth.PasswordChangeView.as_view(template_name='form.html',extra_context={'heading':'Сменить пароль'}),name='password_change'),
    path('password-change/done/',auth.PasswordChangeDoneView.as_view(template_name='registration/password_changed.html'),name='password_change_done'),
    path('team/',accounts.team,name='team'),
    path('invite/<uuid:token>/',accounts.accept_invite,name='accept_invite'),
    path('notifications/',accounts.notifications,name='notifications'),
    path('notifications/<int:notice_id>/read/',accounts.read_notification,name='read_notification'),
    path('manage/',modules.manage_site,name='manage_site'),
    path('catalog/',modules.catalog,name='catalog'),
    path('catalog/new/',modules.item_edit,name='item_create'),
    path('catalog/<int:item_id>/',modules.item_detail,name='item'),
    path('catalog/<int:item_id>/edit/',modules.item_edit,name='item_edit'),
    path('catalog/<int:item_id>/delete/',modules.item_delete,name='item_delete'),
    path('catalog/<int:item_id>/favorite/',modules.favorite,name='favorite'),
    path('favorites/',modules.favorites,name='favorites'),
    path('request/',modules.lead_create,name='lead_create'),
    path('catalog/<int:item_id>/request/',modules.lead_create,name='item_lead'),
    path('requests/<int:lead_id>/status/',modules.lead_status,name='lead_status'),
    path('uploads/new/',modules.upload,name='upload'),
    path('catalog/<int:item_id>/upload/',modules.upload,name='item_upload'),
    path('uploads/<int:asset_id>/',modules.asset,name='asset'),
    path('uploads/<int:asset_id>/delete/',modules.asset_delete,name='asset_delete'),
    path('catalog/<int:item_id>/slots/new/',modules.slot_create,name='slot_create'),
    path('slots/<int:slot_id>/delete/',modules.slot_delete,name='slot_delete'),
    path('slots/<int:slot_id>/book/',modules.book,name='book'),
    path('bookings/',modules.bookings,name='bookings'),
    path('bookings/<int:booking_id>/cancel/',modules.booking_cancel,name='booking_cancel'),
    path('cart/',modules.cart,name='cart'),
    path('cart/<int:item_id>/',modules.cart_update,name='cart_update'),
    path('checkout/',modules.checkout_view,name='checkout'),
    path('orders/',modules.orders,name='orders'),
    path('orders/<int:order_id>/',modules.order_detail,name='order'),
    path('orders/<int:order_id>/pay/',payments.pay,name='pay'),
    path('payments/webhook/',payments.webhook,name='payment_webhook'),
    path('catalog/<int:item_id>/review/',modules.review_edit,name='review'),
    path('reviews/<int:review_id>/moderate/',modules.review_moderate,name='review_moderate'),
    path('pages/',modules.pages,name='pages'),
    path('pages/new/',modules.page_edit,name='page_create'),
    path('pages/<int:page_id>/edit/',modules.page_edit,name='page_edit'),
    path('pages/<int:page_id>/delete/',modules.page_delete,name='page_delete'),
    path('pages/<slug:slug>/',modules.page_detail,name='page'),
]
