from django.contrib.auth import views as auth_views
from django.urls import path
from django.urls import reverse_lazy

from founder import views, workbench_views, lab_views, lab_testing_views, team_views, coin_views


urlpatterns = [
    path('startups/<uuid:startup_id>/lab/', lab_views.lab, name='lab'),
    path('startups/<uuid:startup_id>/lab/generate/', lab_views.lab_generate, name='lab_generate'),
    path('startups/<uuid:startup_id>/lab/customize/', lab_views.lab_customize, name='lab_customize'),
    path('startups/<uuid:startup_id>/lab/backend/create/', lab_views.lab_backend_create, name='lab_backend_create'),
    path('startups/<uuid:startup_id>/lab/backend/stop/', lab_views.lab_stop, name='lab_stop'),
    path('startups/<uuid:startup_id>/lab/<uuid:version_id>/download/', lab_views.lab_download, name='lab_download'),
    path('startups/<uuid:startup_id>/lab/<uuid:version_id>/run/', lab_views.lab_run, name='lab_run'),
    path('startups/<uuid:startup_id>/lab/publish/', lab_testing_views.lab_publish, name='lab_publish'),
    path('community/<uuid:startup_id>/lab/', lab_testing_views.lab_trial, name='lab_trial'),
    path('community/<uuid:startup_id>/lab/<uuid:version_id>/preview/', lab_testing_views.lab_public_preview, name='lab_public_preview'),
    path('community/<uuid:startup_id>/lab/start/', lab_testing_views.lab_test_start, name='lab_test_start'),
    path('community/<uuid:startup_id>/lab/tests/<uuid:session_id>/preview/', lab_testing_views.lab_test_preview, name='lab_test_preview'),
    path('community/<uuid:startup_id>/lab/tests/<uuid:session_id>/events/', lab_testing_views.lab_test_events, name='lab_test_events'),
    path('community/<uuid:startup_id>/lab/tests/<uuid:session_id>/finish/', lab_testing_views.lab_test_finish, name='lab_test_finish'),
    path('startups/<uuid:startup_id>/lab/<uuid:version_id>/preview/', lab_views.lab_preview, name='lab_preview'),
    path('startups/<uuid:startup_id>/tasks/', workbench_views.tasks, name='tasks'),
    path('startups/<uuid:startup_id>/tasks/generate/', workbench_views.tasks_generate, name='tasks_generate'),
    path('startups/<uuid:startup_id>/tasks/<uuid:task_id>/skip/', workbench_views.task_skip, name='task_skip'),
    path('startups/<uuid:startup_id>/evidence/', workbench_views.evidence_list, name='evidence_list'),
    path('startups/<uuid:startup_id>/evidence/new/', workbench_views.evidence_edit, name='evidence_create'),
    path('startups/<uuid:startup_id>/evidence/<uuid:entry_id>/', workbench_views.evidence_edit, name='evidence_edit'),
    path('startups/<uuid:startup_id>/investor/', workbench_views.investor, name='investor'),
    path('startups/<uuid:startup_id>/review/', workbench_views.review, name='review'),
    path('startups/<uuid:startup_id>/review/generate/', workbench_views.review_generate, name='review_generate'),
    path('startups/<uuid:startup_id>/review/<uuid:review_id>/steps/<int:index>/task/', workbench_views.review_step_task,
         name='review_step_task'),
    path('startups/<uuid:startup_id>/team/', team_views.team, name='team'),
    path('startups/<uuid:startup_id>/team/invite/', team_views.team_invite, name='team_invite'),
    path('startups/<uuid:startup_id>/team/<int:member_id>/', team_views.team_member_update, name='team_member_update'),
    path('startups/<uuid:startup_id>/team/leave/', team_views.team_leave, name='team_leave'),
    path('invites/<int:member_id>/', team_views.invite_respond, name='invite_respond'),
    path('startups/<uuid:startup_id>/promote/', coin_views.promote, name='promote'),
    path('startups/<uuid:startup_id>/promote/buy/', coin_views.promote_buy, name='promote_buy'),
    path('startups/<uuid:startup_id>/promote/bounty/', coin_views.bounty_fund, name='bounty_fund'),
    path('startups/<uuid:startup_id>/promote/bounty/<int:bounty_id>/close/', coin_views.bounty_close, name='bounty_close'),
    path('startups/<uuid:startup_id>/bruno/', coin_views.wardrobe, name='wardrobe'),
    path('startups/<uuid:startup_id>/bruno/action/', coin_views.wardrobe_action, name='wardrobe_action'),
    path('startups/<uuid:startup_id>/tasks/<uuid:task_id>/assign/', workbench_views.task_assign, name='task_assign'),
    path('community/<uuid:startup_id>/join/', team_views.join_request, name='join_request'),
    path('coins/', coin_views.wallet, name='wallet'),
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("register/", views.register, name="register"),
    path("login/", auth_views.LoginView.as_view(template_name="registration/login.html"), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("account/password/", auth_views.PasswordChangeView.as_view(
        template_name="registration/password_change_form.html", success_url=reverse_lazy("home"),
    ), name="password_change"),
    path("startups/new/", views.startup_create, name="startup_create"),
    path("startups/<uuid:startup_id>/", views.dashboard, name="dashboard"),
    path("startups/<uuid:startup_id>/edit/", views.startup_edit, name="startup_edit"),
    path("startups/<uuid:startup_id>/metrics/", views.metrics_create, name="metrics_create"),
    path("startups/<uuid:startup_id>/metrics/assess/", views.metrics_assess, name="metrics_assess"),
    path("startups/<uuid:startup_id>/chat/new/", views.chat_create, name="chat_create"),
    path("startups/<uuid:startup_id>/chat/refine/<str:axis>/", views.chat_refine, name="chat_refine"),
    path("startups/<uuid:startup_id>/pitch/new/", views.pitch_create, name="pitch_create"),
    path("startups/<uuid:startup_id>/chat/<uuid:session_id>/", views.chat_detail, name="chat_detail"),
    path("startups/<uuid:startup_id>/chat/<uuid:session_id>/send/", views.chat_send, name="chat_send"),
    path("startups/<uuid:startup_id>/chat/<uuid:session_id>/finish/", views.pitch_finish, name="pitch_finish"),
    path("startups/<uuid:startup_id>/chat/<uuid:session_id>/messages/<uuid:message_id>/feedback/",
         views.message_feedback, name="message_feedback"),
]
