# Generated by Django 6.0.8 on 2026-09-24 10:46

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import founder.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'Пользователь'), ('assistant', 'Ассистент')], max_length=10)),
                ('content', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('cofounder', 'ИИ-сооснователь'), ('pitch', 'Симулятор питча')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=500, upload_to=founder.models.attachment_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField()),
                ('extracted_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='founder.chatmessage')),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='founder.chatsession'),
        ),
        migrations.CreateModel(
            name='PitchReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('summary', models.TextField()),
                ('mistakes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pitch_report', to='founder.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160)),
                ('one_line_pitch', models.CharField(blank=True, max_length=300)),
                ('problem', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('target_customer', models.TextField(blank=True)),
                ('stage', models.CharField(choices=[('idea', 'Идея'), ('validation', 'Проверка'), ('traction', 'Первые результаты'), ('growth', 'Рост')], default='idea', max_length=20)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StartupMetrics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('market', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('finance', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('team', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('pitch', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('assessment_notes', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_snapshots', to='founder.startupprofile')),
            ],
            options={
                'ordering': ['-assessed_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='StartupMemory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('note', 'Заметка'), ('fact', 'Факт'), ('assumption', 'Гипотеза'), ('decision', 'Решение'), ('risk', 'Риск')], default='note', max_length=20)),
                ('content', models.TextField()),
                ('as_of_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('embedding_ref', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('source_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_memories', to='founder.chatmessage')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='founder.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MascotState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('curious', 'Любопытный'), ('sleepy', 'Сонный'), ('focused', 'Сосредоточенный'), ('confident', 'Уверенный')], default='curious', max_length=20)),
                ('outfit', models.CharField(choices=[('hoodie', 'Худи'), ('pajamas', 'Пижама'), ('jacket', 'Пиджак'), ('suit', 'Деловой костюм')], default='hoodie', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mascot_state', to='founder.startupprofile')),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='startup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='founder.startupprofile'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['session', 'created_at'], name='chat_message_order'),
        ),
        migrations.AddConstraint(
            model_name='pitchreport',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__lte', 100)), name='pitch_report_score_range'),
        ),
        migrations.AddIndex(
            model_name='startupmetrics',
            index=models.Index(fields=['startup', '-assessed_at'], name='startup_metrics_recent'),
        ),
        migrations.AddConstraint(
            model_name='startupmetrics',
            constraint=models.CheckConstraint(condition=models.Q(('product__gte', 0), ('product__lte', 100)), name='metrics_product_range'),
        ),
        migrations.AddConstraint(
            model_name='startupmetrics',
            constraint=models.CheckConstraint(condition=models.Q(('market__gte', 0), ('market__lte', 100)), name='metrics_market_range'),
        ),
        migrations.AddConstraint(
            model_name='startupmetrics',
            constraint=models.CheckConstraint(condition=models.Q(('finance__gte', 0), ('finance__lte', 100)), name='metrics_finance_range'),
        ),
        migrations.AddConstraint(
            model_name='startupmetrics',
            constraint=models.CheckConstraint(condition=models.Q(('team__gte', 0), ('team__lte', 100)), name='metrics_team_range'),
        ),
        migrations.AddConstraint(
            model_name='startupmetrics',
            constraint=models.CheckConstraint(condition=models.Q(('pitch__gte', 0), ('pitch__lte', 100)), name='metrics_pitch_range'),
        ),
        migrations.AddIndex(
            model_name='startupmemory',
            index=models.Index(fields=['startup', 'is_active', '-created_at'], name='startup_memory_lookup'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['startup', '-created_at'], name='chat_session_recent'),
        ),
    ]
