# Generated by Django 6.0.8 on 2026-09-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupmetrics',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='startupmetrics',
            name='assessment_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='startupmetrics',
            name='source',
            field=models.CharField(choices=[('manual', 'Оценка основателя'), ('ai', 'Оценка Бруно')], default='manual', max_length=10),
        ),
    ]
