# Generated by Django 6.0.8 on 2026-09-25 14:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0002_startupmetrics_ai_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='focus_axis',
            field=models.CharField(blank=True, choices=[('product', 'Продукт'), ('market', 'Рынок'), ('finance', 'Финансы'), ('team', 'Команда'), ('pitch', 'Ясность идеи')], max_length=12),
        ),
        migrations.AddField(
            model_name='startupmetrics',
            name='assessment_evidence',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='StartupAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40)),
                ('earned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='founder.startupprofile')),
            ],
            options={
                'ordering': ['earned_at'],
                'constraints': [models.UniqueConstraint(fields=('startup', 'code'), name='unique_startup_achievement')],
            },
        ),
    ]
