# Generated by Django 6.0.8 on 2026-09-26 12:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0004_existing_first_radar_achievement'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrunoTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('axis', models.CharField(choices=[('product', 'Продукт'), ('market', 'Рынок'), ('finance', 'Финансы'), ('team', 'Команда'), ('pitch', 'Ясность идеи')], max_length=12)),
                ('title', models.CharField(max_length=160)),
                ('instructions', models.TextField(max_length=1200)),
                ('success_criterion', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('todo', 'В работе'), ('done', 'Выполнено'), ('skipped', 'Отложено')], default='todo', max_length=12)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bruno_tasks', to='founder.startupprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('axis', models.CharField(choices=[('product', 'Продукт'), ('market', 'Рынок'), ('finance', 'Финансы'), ('team', 'Команда'), ('pitch', 'Ясность идеи')], max_length=12, verbose_name='Направление')),
                ('claim', models.CharField(max_length=300, verbose_name='Что проверяли')),
                ('observation', models.TextField(max_length=4000, verbose_name='Что получилось: факты, числа, период')),
                ('source', models.CharField(blank=True, max_length=500, verbose_name='Откуда сведения')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка на источник (необязательно)')),
                ('observed_on', models.DateField(default=django.utils.timezone.localdate, verbose_name='Дата наблюдения')),
                ('outcome', models.CharField(choices=[('supported', 'Гипотеза получила поддержку'), ('refuted', 'Гипотеза не подтвердилась'), ('unclear', 'Пока недостаточно данных')], default='unclear', max_length=12, verbose_name='Результат проверки')),
                ('next_question', models.CharField(blank=True, max_length=500, verbose_name='Что ещё нужно выяснить')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_entries', to='founder.startupprofile')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_entries', to='founder.brunotask')),
            ],
            options={
                'ordering': ['-observed_on', '-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='brunotask',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'todo')), fields=('startup', 'axis'), name='one_open_task_per_axis'),
        ),
    ]
