# Generated by Django 6.0.8 on 2026-09-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0005_bruno_tasks_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitchreport',
            name='mistakes',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
