# Generated by Django 6.0.8 on 2026-09-27 18:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0006_allow_pitch_without_mistakes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Название')),
                ('tagline', models.CharField(blank=True, max_length=240, verbose_name='Идея в одном предложении')),
                ('summary', models.TextField(blank=True, max_length=600, verbose_name='Коротко о проекте')),
                ('problem', models.TextField(blank=True, max_length=400, verbose_name='Проблема')),
                ('solution', models.TextField(blank=True, max_length=400, verbose_name='Решение')),
                ('audience', models.CharField(blank=True, max_length=300, verbose_name='Для кого')),
                ('business_model', models.CharField(blank=True, max_length=300, verbose_name='Как зарабатываем')),
                ('traction', models.TextField(blank=True, max_length=400, verbose_name='Что уже получилось')),
                ('looking_for', models.CharField(blank=True, max_length=300, verbose_name='Кого или что ищем')),
                ('stage', models.CharField(choices=[('idea', 'Идея'), ('validation', 'Проверка'), ('traction', 'Первые результаты'), ('growth', 'Рост')], default='idea', max_length=20, verbose_name='Стадия')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('share_radar', models.BooleanField(default=False, verbose_name='Показывать баллы радара в опубликованной карточке')),
                ('revision', models.PositiveIntegerField(default=0)),
                ('published_data', models.JSONField(blank=True, default=dict)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_card', to='founder.startupprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DirectConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('low_read_id', models.PositiveBigIntegerField(default=0)),
                ('high_read_id', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_high', to=settings.AUTH_USER_MODEL)),
                ('user_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_low', to=settings.AUTH_USER_MODEL)),
                ('source_card', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='founder.projectcard')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.UUIDField()),
                ('content', models.TextField(max_length=4000)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to='founder.directconversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['conversation', 'id'], name='direct_message_history')],
                'constraints': [models.UniqueConstraint(fields=('sender', 'client_id'), name='unique_direct_message_retry')],
            },
        ),
        migrations.CreateModel(
            name='ProjectBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bookmarks', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='founder.projectcard')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'card'), name='unique_project_bookmark')],
            },
        ),
        migrations.AddConstraint(
            model_name='directconversation',
            constraint=models.UniqueConstraint(fields=('user_low', 'user_high'), name='unique_direct_pair'),
        ),
        migrations.AddConstraint(
            model_name='directconversation',
            constraint=models.CheckConstraint(condition=models.Q(('user_low__lt', models.F('user_high'))), name='ordered_direct_pair'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('user', 'blocked'), name='unique_user_block'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('blocked')), _negated=True), name='no_self_block'),
        ),
    ]
