# Generated by Django 6.0.8 on 2026-09-28 08:34

import django.core.validators
import founder.models
from django.db import migrations, models
import re


def assign_existing_handles(apps, schema_editor):
    User = apps.get_model('founder', 'User')
    used = set()
    for user in User.objects.using(schema_editor.connection.alias).order_by('pk').iterator():
        candidate = user.username.lower()
        if not re.fullmatch(r'[a-z][a-z0-9_]{2,31}', candidate):
            candidate = f'founder_{user.pk}'
        base = candidate
        suffix = 1
        while candidate in used:
            tail = f'_{suffix}'
            candidate = base[:32-len(tail)] + tail
            suffix += 1
        used.add(candidate)
        User.objects.using(schema_editor.connection.alias).filter(pk=user.pk).update(handle=candidate)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('founder', '0007_community_cards_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=founder.models.avatar_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=600, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Имя в профиле'),
        ),
        migrations.AddField(
            model_name='user',
            name='handle',
            field=models.CharField(max_length=32, null=True, verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='occupation',
            field=models.CharField(blank=True, max_length=120, verbose_name='Чем занимаетесь'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_website',
            field=models.URLField(blank=True, verbose_name='Сайт или портфолио'),
        ),
        migrations.RunPython(assign_existing_handles, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user', name='handle',
            field=models.CharField(default=founder.models.default_user_handle, max_length=32, unique=True,
                validators=[founder.models.handle_validator], verbose_name='Тег'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('handle__regex', '^[a-z][a-z0-9_]{2,31}$')), name='user_handle_format'),
        ),
    ]
