# Generated by Django 6.0.8 on 2026-10-05 14:23

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0008_member_profiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField(default=dict)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='founder.startupprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
