# Generated by Django 6.0.8 on 2026-10-06 17:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0009_request_protection'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSiteVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt', models.TextField(max_length=2000)),
                ('html', models.TextField(max_length=128000)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='founder.labsiteversion')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_versions', to='founder.startupprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
