# Generated by Django 6.0.8 on 2026-10-06 17:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0009_project_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(choices=[(1, 'Полезно'), (-1, 'Мимо')])),
                ('comment', models.CharField(blank=True, max_length=500, verbose_name='Что было не так')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='founder.chatmessage')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
