# Generated by Django 6.0.8 on 2026-10-06 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0010_lab_site_versions'),
        ('founder', '0010_message_feedback'),
    ]

    operations = [
    ]
