# Generated by Django 6.0.8 on 2026-10-06 22:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0011_merge_0010_lab_site_versions_0010_message_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='speaker',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='mode',
            field=models.CharField(choices=[('cofounder', 'ИИ-сооснователь'), ('pitch', 'Симулятор питча'), ('panel', 'Панель акул')], max_length=20),
        ),
        migrations.CreateModel(
            name='PanelVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.JSONField(default=list)),
                ('ai_model', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panel_verdict', to='founder.chatsession')),
            ],
        ),
    ]
