# Generated by Django 6.0.8 on 2026-10-06 21:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0011_merge_0010_lab_site_versions_0010_message_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_publication', to='founder.startupprofile')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='founder.labsiteversion')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True, max_length=1000)),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_tests', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_sessions', to='founder.labsiteversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabTestEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('ready', 'Страница открылась'), ('click', 'Клик'), ('scroll', 'Прокрутка'), ('form', 'Попытка отправить форму'), ('error', 'Ошибка страницы')], max_length=10)),
                ('target', models.CharField(blank=True, max_length=160)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('depth', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='founder.labtestsession')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='labtestsession',
            index=models.Index(fields=['version', '-created_at'], name='lab_tests_recent'),
        ),
        migrations.AddConstraint(
            model_name='labtestsession',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='lab_rating_range'),
        ),
        migrations.AddConstraint(
            model_name='labtestevent',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='lab_event_sequence'),
        ),
    ]
