# Generated by Django 6.0.8 on 2026-10-07 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0012_labpublication_labtestsession_labtestevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsiteversion',
            name='kind',
            field=models.CharField(choices=[('static', 'Статический сайт'), ('django', 'Django: аккаунты и чаты')], default='static', max_length=10),
        ),
    ]
