# Generated by Django 6.0.8 on 2026-10-07 15:52

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0013_lab_site_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabSpendBucket',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('micro_rub', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='labsiteversion',
            name='edit_method',
            field=models.CharField(default='full', max_length=20),
        ),
        migrations.AddField(
            model_name='labsiteversion',
            name='generation_key',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='labsiteversion',
            name='presentation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='LabAIUsage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=100)),
                ('operation', models.CharField(default='code', max_length=20)),
                ('status', models.CharField(default='reserved', max_length=20)),
                ('input_bound', models.PositiveIntegerField()),
                ('output_limit', models.PositiveIntegerField()),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('input_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('output_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('accounted_micro_rub', models.PositiveBigIntegerField()),
                ('bucket_keys', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='founder.startupprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='founder.labsiteversion')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'created_at'], name='lab_usage_user_date')],
            },
        ),
    ]
