# Generated by Django 6.0.8 on 2026-10-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0014_lab_ai_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='labsiteversion',
            name='backend_modules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
