# Generated by Django 6.0.8 on 2026-10-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0015_lab_backend_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labsiteversion',
            name='kind',
            field=models.CharField(choices=[('static', 'Статический сайт'), ('django', 'Django: готовые модули')], default='static', max_length=10),
        ),
    ]
