# Generated by Django 6.0.10.dev20261009120642 on 2026-10-10 19:16

import django.db.models.deletion
import django.utils.timezone
import founder.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("founder", "0018_selectable_base_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="DirectAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Изображение"), ("file", "Файл")],
                        max_length=10,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500, upload_to=founder.models.direct_attachment_path
                    ),
                ),
                (
                    "preview",
                    models.FileField(
                        blank=True,
                        max_length=500,
                        upload_to=founder.models.direct_attachment_path,
                    ),
                ),
                ("original_name", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                ("size_bytes", models.PositiveBigIntegerField()),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="founder.directconversation",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="founder.directmessage",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="direct_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["uploader", "message", "created_at"],
                        name="direct_attachment_pending",
                    )
                ],
            },
        ),
    ]
