# Generated by Django 6.0.9 on 2026-10-08 08:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


WELCOME_BONUS = 50


def backfill(apps, schema_editor):
    """Существующим аккаунтам — стартовый бонус; старые сообщения чата писал владелец."""
    User = apps.get_model("founder", "User")
    CoinTransaction = apps.get_model("founder", "CoinTransaction")
    ChatMessage = apps.get_model("founder", "ChatMessage")
    StartupProfile = apps.get_model("founder", "StartupProfile")
    for user in User.objects.all().iterator():
        _, created = CoinTransaction.objects.get_or_create(
            key=f"welcome:{user.pk}",
            defaults={"user": user, "amount": WELCOME_BONUS, "kind": "welcome", "note": "Стартовый бонус"},
        )
        if created:
            User.objects.filter(pk=user.pk).update(coins=models.F("coins") + WELCOME_BONUS)
    for startup in StartupProfile.objects.all().iterator():
        ChatMessage.objects.filter(session__startup=startup, role="user", author__isnull=True).update(
            author_id=startup.owner_id)


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0018_selectable_base_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='coins',
            field=models.PositiveIntegerField(default=0, verbose_name='Монеты'),
        ),
        migrations.CreateModel(
            name='CoinTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('kind', models.CharField(choices=[('welcome', 'Стартовый бонус'), ('chat', 'Разговор с Бруно'), ('pitch', 'Тренировка питча'), ('evidence', 'Запись в дневнике'), ('task', 'Выполненное задание'), ('test', 'Тест чужого прототипа'), ('promotion', 'Продвижение проекта'), ('adjustment', 'Корректировка')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('key', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_transactions', to='founder.startupprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['user', 'kind', 'created_at'], name='coin_tx_user_kind_date')],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('editor', 'Соавтор'), ('viewer', 'Наблюдатель')], default='editor', max_length=10, verbose_name='Роль')),
                ('status', models.CharField(choices=[('invited', 'Приглашён'), ('active', 'Участник')], default='invited', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='founder.startupprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('startup', 'user'), name='unique_project_member')],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('feed_top', 'Поднять карточку в ленте'), ('highlight', 'Выделить карточку'), ('testers', 'Позвать тестировщиков')], max_length=12)),
                ('cost', models.PositiveIntegerField()),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('bought_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='founder.startupprofile')),
            ],
            options={
                'ordering': ['-ends_at', '-id'],
                'indexes': [models.Index(fields=['kind', 'ends_at'], name='promotion_active')],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
