# Generated by Django 6.0.9 on 2026-10-09 10:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0019_collaboration_and_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='brunotask',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mascotstate',
            name='accessories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='message',
            field=models.CharField(blank=True, max_length=500, verbose_name='О себе и чем поможете'),
        ),
        migrations.AlterField(
            model_name='cointransaction',
            name='kind',
            field=models.CharField(choices=[('welcome', 'Стартовый бонус'), ('chat', 'Разговор с Бруно'), ('pitch', 'Тренировка питча'), ('evidence', 'Запись в дневнике'), ('task', 'Выполненное задание'), ('test', 'Тест чужого прототипа'), ('streak', 'Серия дней подряд'), ('bounty', 'Награда от автора прототипа'), ('promotion', 'Продвижение проекта'), ('outfit', 'Гардероб Бруно'), ('bounty_fund', 'Награда тестировщикам'), ('refund', 'Возврат остатка награды'), ('adjustment', 'Корректировка')], max_length=12),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='status',
            field=models.CharField(choices=[('invited', 'Приглашён'), ('requested', 'Подал заявку'), ('active', 'Участник')], default='invited', max_length=10),
        ),
        migrations.CreateModel(
            name='TestBounty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward', models.PositiveIntegerField()),
                ('remaining', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('funder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_bounties', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_bounties', to='founder.startupprofile')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MascotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('bought_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascot_items', to='founder.startupprofile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('startup', 'code'), name='unique_mascot_item')],
            },
        ),
        migrations.CreateModel(
            name='ProjectActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('radar', 'Радар'), ('chat', 'Разговор'), ('pitch', 'Питч'), ('task', 'Задания'), ('evidence', 'Дневник'), ('review', 'Разбор'), ('card', 'Карточка'), ('lab', 'Лаборатория'), ('team', 'Команда'), ('coins', 'Монеты')], max_length=10)),
                ('text', models.CharField(max_length=240)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='founder.startupprofile')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['startup', '-created_at'], name='project_activity_recent')],
            },
        ),
    ]
