# Generated by Django 6.0.9 on 2026-10-08 17:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0019_merge_shark_panel_base_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('test', models.CharField(max_length=500)),
                ('axis', models.CharField(choices=[('product', 'Продукт'), ('market', 'Рынок'), ('finance', 'Финансы'), ('team', 'Команда'), ('pitch', 'Ясность идеи')], max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas', to='founder.chatmessage')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_ideas', to='founder.startupprofile')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='founder.brunotask')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.JSONField(blank=True, default=dict)),
                ('gap', models.CharField(blank=True, max_length=300)),
                ('moves', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='founder.startupprofile')),
            ],
        ),
    ]
