# Generated by Django 6.0.8 on 2026-10-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('founder', '0019_lab_version_bruno_report'),
        ('founder', '0020_card_reports'),
        ('founder', '0020_wardrobe_bounties_requests_activity'),
        ('founder', '0021_market_report'),
    ]

    operations = [
    ]
